spring.application.name=backend

# ==========================================
# MongoDB Configuration
# ==========================================
spring.data.mongodb.uri=mongodb://localhost:27017/backend
spring.data.mongodb.auto-index-creation=true

# ==========================================
# Logger Configuration
# ==========================================
logging.file.name=logs/backend.log

logging.level.root=INFO

# Rotate logs when they reach 10 MB
logging.logback.rollingpolicy.max-file-size=10MB

# Keep the last 7 log files
logging.logback.rollingpolicy.max-history=7

# ==========================================
# Server Configuration
# ==========================================
server.port=9092


#===================================================
jwt.secret=jhfafjugsfkjagkfiuaghkjbajnfvkaufiaf,jbfkaugfiahfajfvkadfkafjuaf
#===================================================
jwt.expiration=86400000