spring.application.name=backend

# ==========================================
# MySQL Configuration
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mohit
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# MongoDB Configuration
# ==========================================
spring.data.mongodb.uri=mongodb://localhost:27017/backend
spring.data.mongodb.auto-index-creation=true

# ==========================================
# Logger Configuration
# ==========================================
logging.file.name=logs/backend.log

logging.level.root=INFO

# Rotate logs when they reach 10 MB
logging.logback.rollingpolicy.max-file-size=10MB

# Keep the last 7 log files
logging.logback.rollingpolicy.max-history=7

# ==========================================
# Server Configuration
# ==========================================
server.port=9092


#===================================================
jwt.secret=jhfafjugsfkjagkfiuaghkjbajnfvkaufiaf,jbfkaugfiahfajfvkadfkafjuaf 
#===================================================