services:

  #########################################
  # FRONTEND
  #########################################
  frontend:
    container_name: fitfusion-frontend
    image: ${DOCKER_USERNAME:-mohitchavan1304}/fitfusion-frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - fitfusion-network

  #########################################
  # API GATEWAY
  #########################################
  api-gateway:
    container_name: api-gateway
    image: ${DOCKER_USERNAME:-mohitchavan1304}/fitfusion-api-gateway:latest
    build:
      context: ./backend/ApiGateway
    ports:
      - "8085:8085"
    environment:
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: http://order-service:9090
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_URI: http://user-service:9091
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_2_URI: http://catalog-service:9092
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_3_URI: http://ai-chatbot:8000
    depends_on:
      - user-service
      - catalog-service
      - order-service
      - ai-chatbot
    restart: unless-stopped
    networks:
      - fitfusion-network

  #########################################
  # USER SERVICE
  #########################################
  user-service:
    container_name: user-service
    image: ${DOCKER_USERNAME:-mohitchavan1304}/fitfusion-user-service:latest
    build:
      context: ./backend/UserService
    ports:
      - "9091:9091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userservice?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_PASSWORD: manager
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - fitfusion-network

  #########################################
  # CATALOG SERVICE
  #########################################
  catalog-service:
    container_name: catalog-service
    image: ${DOCKER_USERNAME:-mohitchavan1304}/fitfusion-catalog-service:latest
    build:
      context: ./backend/CatalogInventoryService/backend
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/backend
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - fitfusion-network

  #########################################
  # ORDER SERVICE
  #########################################
  order-service:
    container_name: order-service
    image: ${DOCKER_USERNAME:-mohitchavan1304}/fitfusion-order-service:latest
    build:
      context: ./backend/OrderService
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fitfusion_order_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_PASSWORD: manager
      SERVICE_USER_BASE_URL: http://user-service:9091
      SERVICE_CATALOG_BASE_URL: http://catalog-service:9092
      SERVICE_INVOICE_BASE_URL: http://print-invoice-service:8082
    depends_on:
      - mysql
      - user-service
      - catalog-service
      - print-invoice-service
    restart: unless-stopped
    networks:
      - fitfusion-network

  #########################################
  # AI CHATBOT
  #########################################
  ai-chatbot:
    container_name: ai-chatbot
    image: ${DOCKER_USERNAME:-mohitchavan1304}/fitfusion-ai-chatbot:latest
    build:
      context: ./backend/AiChatbot
    ports:
      - "8000:8000"
    environment:
      CATALOG_SERVICE_URL: http://catalog-service:9092
    env_file:
      - ./backend/AiChatbot/.env
    depends_on:
      - catalog-service
    restart: unless-stopped
    networks:
      - fitfusion-network
  
  #########################################
  # PRINT INVOICE SERVICE (.NET)
  #########################################
  print-invoice-service:
    container_name: print-invoice-service
    image: ${DOCKER_USERNAME:-mohitchavan1304}/fitfusion-print-invoice-service:latest
    build:
      context: ./backend/PrintInvoiceService
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - fitfusion-network

  #########################################
  # MYSQL
  #########################################
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: fitfusion
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - fitfusion-network

  #########################################
  # MONGODB
  #########################################
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - fitfusion-network

volumes:
  mysql-data:
  mongo-data:

networks:
  fitfusion-network:
    driver: bridge
