spring.application.name=OrderService

#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/fitfusion_order_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=manager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
server.port=9090

razorpay.key.id=rzp_test_MOCKKEY123456
razorpay.key.secret=mock_secret_key_for_testing_only_12345
razorpay.webhook.secret=mock_webhook_secret_67890
