spring.application.name=api-gateway
server.port=8085

# ---------- CORS ----------
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

# ---------- Order Service routes ----------
spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:9090
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/orders/**,/api/payments/**,/api/payouts/**,/api/return-requests/**,/api/return-actions/**,/api/refunds/**,/api/exchanges/**

# ---------- User Service routes ----------
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:9091
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**,/api/commission-rules/**,/api/discount-rules/**,/api/users/**,/api/retailers/**,/api/addresses/**,/api/admin/**

# ---------- Catalog Service routes ----------
spring.cloud.gateway.server.webflux.routes[2].id=catalog-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:9092
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/inventory/**,/api/products/**,/api/categories/**,/api/subcategories/**,/api/brands/**,/api/attribute/**